package view;

import javax.swing.JOptionPane;
import model.Emprestimo;

public class FrmCadastrarEmprestimo extends javax.swing.JFrame {

    private Emprestimo objetoEmprestimo;
    
    public FrmCadastrarEmprestimo() {
        initComponents();
        this.objetoEmprestimo = new Emprestimo();
        this.carregarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dropdownAmigos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dropdownFerramentas = new javax.swing.JComboBox<>();
        mensagemEmprestimo = new javax.swing.JLabel();
        btnEmprestar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        inputDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Empréstimos");
        setResizable(false);

        dropdownAmigos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pedro", "Matheus", "Tulio", "Heitor", "Thuysa", "JP", "Teste", "Pedro", "Matheus", "Tulio", "Heitor", "Thuysa", "JP", "Teste" }));
        dropdownAmigos.setToolTipText("Nome do Amigo");
        dropdownAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownAmigosActionPerformed(evt);
            }
        });

        jLabel1.setText("Amigos:");

        jLabel2.setText("Ferramentas:");

        dropdownFerramentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Machado", "Broca", "Machadinha", "Parafusadeira", "Chave de Fenda" }));
        dropdownFerramentas.setToolTipText("Ferramenta do empréstimo");
        dropdownFerramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownFerramentasActionPerformed(evt);
            }
        });

        mensagemEmprestimo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnEmprestar.setText("Emprestar");
        btnEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        inputDate.setText("26/05/2024");
        inputDate.setToolTipText("Data de devolução");

        jLabel3.setText("Data Limite:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3))
                    .addComponent(btnEmprestar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(mensagemEmprestimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(dropdownAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(dropdownFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(inputDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dropdownAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropdownFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(mensagemEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnEmprestar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestarActionPerformed
        try {
            String amigo = dropdownAmigos.getSelectedItem().toString();
            String ferramenta = dropdownFerramentas.getSelectedItem().toString();
            
            mensagemEmprestimo.setText(amigo + " irá pegar " + ferramenta + " emprestado até " + inputDate + ", certo?");
            
            if(amigo.isEmpty()) {
                throw new Mensagem("Selecione um amigo para prosseguir!");
            }
            
            if(ferramenta.isEmpty()) {
                throw new Mensagem("Selecione um amigo para prosseguir!");
            }
//            if (this.inputNome.getText().length() < 2) {
//                throw new Mensagem("Nome deve conter ao menos 2 caracteres.");
//            } else {
//                nome = this.inputNome.getText();
//            }
//
//            if (this.inputTelefone.getText().length() < 11) {
//                throw new Mensagem("Telefone deve conter ao menos 11 caracteres.");
//            } else {
//                telefone = this.inputTelefone.getText();
//                
//                String ddd = telefone.substring(0, 2);
//                String primeirosDigitos = telefone.substring(2, 7);
//                String ultimosDigitos = telefone.substring(7, 11);
//                
//                telefone = "(" + ddd + ") " + primeirosDigitos + "-" + ultimosDigitos;
//            }
//
//            if (this.objetoamigo.insertAmigoBD(nome, telefone)) {
//                JOptionPane.showMessageDialog(null, "Amigo cadastrada com sucesso!");
//                this.inputNome.setText("");
//                this.inputTelefone.setText("");
//            }
            
//        } catch (Mensagem erro) {
//            JOptionPane.showMessageDialog(null, erro.getMessage());
//        } catch (NumberFormatException erro2) {
//            JOptionPane.showMessageDialog(null, "Informe um número válido.");
        } catch (Mensagem error) {
            throw new Error(error);
        }
    }//GEN-LAST:event_btnEmprestarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void dropdownAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownAmigosActionPerformed
        String amigo = dropdownAmigos.getSelectedItem().toString();
        String ferramenta = dropdownFerramentas.getSelectedItem().toString();
        String inputDate = this.inputDate.getText();
            
        mensagemEmprestimo.setText(amigo + " irá pegar " + ferramenta + " emprestado até " + inputDate + ", certo?");
    }//GEN-LAST:event_dropdownAmigosActionPerformed

    private void dropdownFerramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownFerramentasActionPerformed
        String amigo = dropdownAmigos.getSelectedItem().toString();
        String ferramenta = dropdownFerramentas.getSelectedItem().toString();
        String inputDate = this.inputDate.getText();
            
        mensagemEmprestimo.setText(amigo + " irá pegar " + ferramenta + " emprestado até " + inputDate + ", certo?");
    }//GEN-LAST:event_dropdownFerramentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastrarEmprestimo().setVisible(true);
            }
        });
    }
    
    public void carregarDados() {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEmprestar;
    private javax.swing.JComboBox<String> dropdownAmigos;
    private javax.swing.JComboBox<String> dropdownFerramentas;
    private javax.swing.JTextField inputDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel mensagemEmprestimo;
    // End of variables declaration//GEN-END:variables
}
